project_id = "hxfzgjxwozzuzgdsrrpb"

[functions.generate-tool]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.generate-case]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.list-invited-users]
verify_jwt = false

[functions.send-metrics-to-hub]
verify_jwt = false

[functions.purchase-tool]
verify_jwt = false

[functions.expire-inactive-rooms]
verify_jwt = false
